### ISSUE TITLE
Access to remote SignalR Server

### ISSUE THREAD

**Issue by VictorRodriguez88** [aspnet/SignalR-Server#110]
Hi, I'm new in this site, I'm developing a application using SignalR, everything works great in my local machine, but I can't access to the Remote SignalrR Server.

I hope you could help me.

Regards!

**Comment by moozzyk** [comment]
Probably a port is not open in firewall. bwt. the best place to ask this kind of questions is stackoverflow. Closing as this is not an issue with SignalR per se.

**Comment by VictorRodriguez88** [comment]
Thank you for your answer. I found the problem. In my case visual studio has to Be runned as administrator before deploy the server, in my case I'm using one click. The url has to Be the server ip or the DNS.

Regards

**Comment by BrannonKing** [comment]
In order to open a port on Windows you have to be running with Administrative privileges or you have to have the port reserved. You can use the "netsh http add urlacl" command to reserve ports. When you run Visual Studio with administrative privileges then the programs you are debugging inherit the same privilege.
