### ISSUE TITLE
No rc1 nuget package has been published

### ISSUE THREAD

**Issue by Sebazzz** [aspnet/SignalR-Server#144]
Noticed that on nuget.org no rc1 nuget package of SignalR has been published, which pretty much makes it impossible to use in an RC1 level project. Am I missing something?

**Comment by Yaroslav-Fursov** [comment]
In RC1 they made a breaking change!
Microsoft.Framework.* has been renamed to Microsoft.Extensions.*
https://github.com/aspnet/Announcements/issues/77
And now it is not possible to use SignalR 3 in Asp.Net 5 RC1 project because of namespace conflict.
In perticular for IServiceCollection in Startup class.
Are you going to rename namespace in this project soon? Is any workaround exists?

**Comment by andreigorlov** [comment]
Microsoft.AspNet.SignalR.Server 3.0.0-rc1-final can be found here: https://www.myget.org/gallery/aspnetmaster

**Comment by Sebazzz** [comment]
Thanks, that worked! Any reason why the package was not published on nuget.org like the other versions?

Date: Mon, 14 Dec 2015 01:36:11 -0800

**Comment by jeffputz** [comment]
+1 on this. I don't mind if we don't have RTM parity with the rest of ASP.NET, but the namespace change is very breaky, and I'd love to stay as current as possible in my project without having to do manual builds or non-standard package sources.

**Comment by django43ru** [comment]
And with 3.0.0-rc2- version we have a new problem: System.TypeLoadException: there isn't an implemention the method "get_Configuration" of the type Microsoft.AspNet.Hosting.HostingEnvironment from the assembly Microsoft.AspNet.Hosting, Version=1.0.0.0.0 etc...

**Comment by davidfowl** [comment]
> +1 on this. I don't mind if we don't have RTM parity with the rest of ASP.NET, but the namespace change is very breaky, and I'd love to stay as current as possible in my project without having to do manual builds or non-standard package sources.

We're putting minimal engineering effort into SignalR to keep it working with the current builds but there's no real testing happening. If you want to get working bits then you have to use non standard package feeds. We're not publishing this to nuget.org because we don't have the bandwidth to make sure it works as well as it should with the rest of the stack.

Not publishing to nuget.org *is* making that statement. It's not ready yet. There will be large changes to SignalR when it's fully ASP.NET 5 compatible.

**Comment by jeffputz** [comment]
That's fair, it's just an adjustment in the new world of non-big-bang releases, and a little harder for early adopters. Plus there's a little panic about, "OMG they're not paying as much attention to this, is it going away?" Some perceptions, real or not, live on. :)

**Comment by davidfowl** [comment]
That's fine, we just need to maybe put something on the repository that we can point to that is more front and center so we can avoid answering the same thing over and over and over....

**Comment by andreigorlov** [comment]
> And with 3.0.0-rc2-16088 version we have a new problem: System.TypeLoadException: there isn't an implemention the method "get_Configuration" of the type Microsoft.AspNet.Hosting.HostingEnvironment from the assembly Microsoft.AspNet.Hosting, Version=1.0.0.0.0 etc...

https://github.com/aspnet/Home/issues/1138#issuecomment-160512680

**Comment by django43ru** [comment]
I,m sorry for my stupid replic, I was a little bit angry, may be, because I really need SignalR, and I want use asp.net 5)

**Comment by Yaroslav-Fursov** [comment]
So new SignalR is not part of ASP.Net 5 yet ?! I was expecting that RC1 will have it all new: MVC + Web API + SignalR.

**Comment by davidfowl** [comment]
You'll have a wait for it. It won't be done in time. Check the roadmap for more details

**Comment by jeffputz** [comment]
Having to wait for Q3 for SignalR means waiting until then to adopt ASP.NET5 on a number of projects. Not gonna lie, that's a bummer. I mean, it is what it is, I'm not really being critical, just disappointed.

**Comment by davidfowl** [comment]
I am too, but that's the reality of the situation.

**Comment by Yaroslav-Fursov** [comment]
I am very disappointed with this approach. You say that SignalR is not ready yet and will not be ready for more that 6 months. Even worse: after this time it will significantly change!
From my point of view this is the blocker for new ASP.Net projects! No reason to start new project on old ASP.Net because the new one is coming and migration will be painfull. And no reason to start new project on new ASP.Net beacuse "it is not ready yet" and if we use it we will need to re-implement after it will be changed.
Where I can find the roadmap you mentioned and how to find out is there plans for future breaking changes in ASP.Net 5 in general and SignalR in particular?
I am starting new project and need to understand the risks. I was thinking that since ASP.Net 5 is at RC stage it will be less painfull to use it for new project and handle any problems that complete web application on ASP.Net 4 and then migrate all to ASP.Net 5. Now I am in doubts.

**Comment by davidfowl** [comment]
https://github.com/aspnet/Home/wiki/Roadmap

**Comment by dlebedynskyi** [comment]
plan not to release signalr is bumper for us. I know that you guys have your busy roadmap, but no signalR as RC makes blocker for our project on core.

**Comment by tmds** [comment]
+1

> plan not to release signalr is bumper for us. I know that you guys have your busy roadmap, but no signalR as RC makes blocker for our project on core.

Same here. Hope SignalR RC comes soon once dotnet 1.0 is out.

**Comment by davidfowl** [comment]
It's not going to be RC right after 1.0 comes out. I can say that with confidence. It's going to be reworked and will not remain as is

**Comment by tmds** [comment]
@davidfowl Thanks for the response. I prefer having a signalr soon with an API that will change for sure than not being able to adopt aspnet core because there is no websocket middleware. This early version could be a signalr core dev version or perhaps something built based on the rc1 work that was done earlier? SignalR type middelware is a must to build modern reactive web apps. Looking forward to an updated planning on the SignalR stuff (once we have dotnet 1.0).

**Comment by jeffputz** [comment]
I'm surprised at how much I've come to depend on SignalR myself. I can't really start to move to Core without it, though as long as the namespaces and what not are correct, whatever alpha/beta is there will certainly be "good enough" for many months, I suspect.

**Comment by oising** [comment]
I sure hope the client dependency on jQuery goes away too.

**Comment by muratg** [comment]
We started working on SignalR Core. We plan to release a preview soon.
